# 简单示例
# https://github.com/game-ci/unity-builder/blob/main/.github/workflows/build-tests.yml
name: BuildUnityApp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: BuildUnityApp
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk.
          - WebGL # WebGL.
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out
      - uses: actions/checkout@v2
                              
      # Cache Library
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library 
          
      # Test 暂时屏蔽
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
       # env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
       #   githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        env:
        # secrets.UNITY_LICENSE其实是仓库的setting下的secrets的一个key为UNITY_LICENSE的value
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # https://github.com/game-ci/unity-builder/blob/main/.github/workflows/build-tests.yml
      # 简单示例

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: UnityApp (${{ matrix.targetPlatform }})
          path: build
       
       # 通知
      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ secrets.PUSHNOTIFICATIONKEY }}
          MESSAGE: "Notification from GitHub by cuibinbin!"
          TITLE: 任务完成，请验收 
          LINK: https://github.com/3-Delta/Unity-DeviceSafeArea/actions/runs/1036633338

